### ISSUE TITLE
Link is broken in pypi.org

### ISSUE THREAD

**Issue by alexbartz** [hipster-philology/nlp-pie-taggers#22]
The homepage link in https://pypi.org/project/pie-extended/ is currently directing to the dead link https://github.com/ponteineptique/nlp-pie-taggers.

**Comment by PonteIneptique** [comment]
Thanks !

**Comment by PonteIneptique** [comment]
It should be fixed in the next release, per commit https://github.com/hipster-philology/nlp-pie-taggers/commit/f3dd5197cd0a70381e008ab8239d47aff04c9737
