### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by glorieux-f** [hipster-philology/nlp-pie-taggers#38]
extended_pie installed by pip
On every call, a non breaking message is send, seems to come from pie lib

`>>> import  pie_extended.cli.utils`
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by PonteIneptique** [comment]
Hi,
This should not worry you, it's an old "feature" that we should definitely remove...
